### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by lorenzoFabbri** [danigm/hide-minimized#19]
I am using Ubuntu 22.04.3 LTS with GNOME version 42.9 (Wayland), but I am having issues with getting this extension to work. Specifically, it's saying that the current versionof GNOME does not support it:
![image](https://github.com/danigm/hide-minimized/assets/22343884/bc76a415-b352-46bd-9e3e-78da8bc50f53)

**Comment by danigm** [comment]
You can get older version from [extensions.gnome.org](https://extensions.gnome.org/extension/2639/hide-minimized/).

There's a version there for gnome 42, so that should work. In other case you can get the latest code for the extension that should work in GNOME 42 from this commit: https://github.com/danigm/hide-minimized/tree/971225c23d38a875e4f7f9ab2e653730706044c8

I don't have tags or branches in this repository, just the last version, but this doesn't change a lot, so it's easy to check the history and find the correct version.

**Comment by danigm** [comment]
I've just added some tags, so it should be easier to find the exact version: https://github.com/danigm/hide-minimized/tags
